name: Rust

on:
  push: {}

env:
  RUST_BACKTRACE: 1

jobs:
  not-nocapture:
    name: cargo test --verbose
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v3
    - run: cargo test --verbose
  nocapture:
    name: cargo test --verbose -- --nocapture
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v3
    - run: cargo test --verbose -- --nocapture
